steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/${PROJECT_ID}/gce-container-sample',
  '--build-arg', 'GIT_MAIL=${_GIT_MAIL}', '--build-arg', 'GIT_USER=${_GIT_USER}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/${PROJECT_ID}/gce-container-sample']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'compute', 'instances', 'update-container', 'gce-container-sample',
  '--zone', 'asia-northeast1-a',
  '--container-image', 'asia.gcr.io/${PROJECT_ID}/gce-container-sample']
